// Generated by gencpp from file car_msgs/CarCmd.msg
// DO NOT EDIT!


#ifndef CAR_MSGS_MESSAGE_CARCMD_H
#define CAR_MSGS_MESSAGE_CARCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace car_msgs
{
template <class ContainerAllocator>
struct CarCmd_
{
  typedef CarCmd_<ContainerAllocator> Type;

  CarCmd_()
    : header()
    , a(0.0)
    , delta(0.0)  {
    }
  CarCmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , a(0.0)
    , delta(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _a_type;
  _a_type a;

   typedef double _delta_type;
  _delta_type delta;





  typedef boost::shared_ptr< ::car_msgs::CarCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::car_msgs::CarCmd_<ContainerAllocator> const> ConstPtr;

}; // struct CarCmd_

typedef ::car_msgs::CarCmd_<std::allocator<void> > CarCmd;

typedef boost::shared_ptr< ::car_msgs::CarCmd > CarCmdPtr;
typedef boost::shared_ptr< ::car_msgs::CarCmd const> CarCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::car_msgs::CarCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::car_msgs::CarCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::car_msgs::CarCmd_<ContainerAllocator1> & lhs, const ::car_msgs::CarCmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.a == rhs.a &&
    lhs.delta == rhs.delta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::car_msgs::CarCmd_<ContainerAllocator1> & lhs, const ::car_msgs::CarCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace car_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::car_msgs::CarCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::car_msgs::CarCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_msgs::CarCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::car_msgs::CarCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_msgs::CarCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::car_msgs::CarCmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::car_msgs::CarCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e19a807f13f32a7ea46f4837ebb5296d";
  }

  static const char* value(const ::car_msgs::CarCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe19a807f13f32a7eULL;
  static const uint64_t static_value2 = 0xa46f4837ebb5296dULL;
};

template<class ContainerAllocator>
struct DataType< ::car_msgs::CarCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "car_msgs/CarCmd";
  }

  static const char* value(const ::car_msgs::CarCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::car_msgs::CarCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 a\n"
"float64 delta\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::car_msgs::CarCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::car_msgs::CarCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.a);
      stream.next(m.delta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::car_msgs::CarCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::car_msgs::CarCmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
    s << indent << "delta: ";
    Printer<double>::stream(s, indent + "  ", v.delta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAR_MSGS_MESSAGE_CARCMD_H
